use std::io::Cursor;
use std::path::{Path, PathBuf};

use rocket::response::stream::{Event, EventStream};
use rocket::{Data, Response, Route, State};
use rocket::fs::NamedFile;
use rocket::http::{Status, Cookie, CookieJar};
use rocket::Catcher;
use rocket::response::{Redirect, Responder};

use rocket::serde::json::Json;
use rocket::tokio::select;

use paste::paste;

use crate::dyn_content::*;
use crate::models::*;
use crate::capture::*;
use crate::{MASTER_KEY, EventChannels};

// TODO use macro or lazy_static
pub fn routes() -> Vec<Route> {
    routes![
        // Redirection to frontend
        // front_redirect,
        // front_index_fix,

        // Api
        add,
        delete,
        me,
        login_post,
        get_requests,
        get_routes,
        other_backcall,
        listen_captured_reqs,

        // Dispatcher routes ; could've used a macro tbh
        dispatcher_get,
        debug_dispatcher_get,
        dispatcher_head,
        debug_dispatcher_head,
        dispatcher_options,
        debug_dispatcher_options,
        dispatcher_put,
        debug_dispatcher_put,
        dispatcher_delete,
        debug_dispatcher_delete,
        dispatcher_post,
        debug_dispatcher_post,
        dispatcher_patch,
        debug_dispatcher_patch,
    ]
}

// TODO use macro or lazy_static
pub fn catchers() -> impl Into<Vec<Catcher>> {
    catchers![
        page404
    ]
}

// Fix /front broken route using rank < 10
#[get("/front")]
fn front_index_fix() -> Redirect {
    Redirect::to(uri!("/front/home"))
}

// Front redirection fallback in case of unmatched file
#[get("/front/<_..>", rank = 11)]
async fn front_redirect() -> Result<Option<NamedFile>, Redirect> {
    Ok(NamedFile::open(Path::new("../frontend/dist/index.html")).await.ok())
}

/*
 "/backapi/<any..>" is reserved for internal backend usage. Logged-in required, except /backapi/login
    and /backapi/capture, which calls the dispatcher (This can useful for debugging when starting the app from the front server).
    the other route are there to modify the app routes, fetch the captured requests, etc.
 /<path..> matches dynamically defined routes, with headers etc.
*/

/*
 * Implement Responder trait for RouteDefinition. This allows to:
 *  - return a RouteDefinition directly from any route ;
 *  - define the raw Response, given a RouteDefinition
*/
impl<'a> Responder<'a, 'static> for RouteDefinition {
    
    fn respond_to(self, _incoming_req: &'a rocket::Request<'_>) -> Result<rocket::Response<'static>, Status> {
        // Using this trait gives access to the incoming request.
        // TODO dynamic response to request might lay here.
        // Capturing doesn't seems possible here though, as the CapturedRequest cannot be ".complete"-d easily
        // (I mean, maybe it could be, but it would be more painful than letting the routes to it)

        Ok(Response::build()
            .status(Status::new(self.status_code))
            .raw_header("Content-Type", self.content_type)
            .sized_body(self.response_body.len(), Cursor::new(self.response_body))
            .finalize()
        )
    }
}

/* 
 * Dispatcher: anything unmatched lands here, where it gets dispatched,
 * whether according to dynamically defined routes, or saved and sent to the mainpage.
 */
fn dispatch(path: &str) -> RouteDefinition {
    let route_opt = get_content(path);
    if let Some(route) = route_opt {
        route
    } else {
        // TODO use mut value that can be modified by user
        RouteDefinition {
            route: "DEFAULT".to_string(),
            description: "default route".to_string(),
            status_code: 200,
            content_type: "".to_string(),
            response_body: "".to_string()
        }
    }
    
}

// The routes will be generated by macros,
// because Rocket doesn't allow multiple HTTP Method for a same route struct.
macro_rules! dispatch_route_normal {
    ($method:ident) => {
        paste! {
            #[$method("/<path..>", data="<body>", format = "*/*", rank = 100)]
            async fn [< dispatcher_ $method >](path: Option<PathBuf>, body: Data<'_>, req: CapturedRequest, channels: &State<EventChannels>) -> RouteDefinition {
                let path_str: String = match path {
                    Some(p) => String::from("/") + &p.display().to_string(),
                    None => String::from("/"),
                };
    
                capture(req, &path_str, body, channels).await;
                dispatch(&path_str)
            }
        }
    }
}

macro_rules! dispatcher_route_debug {
    ($method:ident) => {
        paste! {
            #[$method("/backapi/capture", data="<body>")]
            async fn [< debug_dispatcher_ $method >](body: Data<'_>, req: CapturedRequest, channels: &State<EventChannels>) -> RouteDefinition {
                capture(req, "/backapi/capture", body, channels).await;
                dispatch("/backapi/capture")
            }
        }
    }
}

// Recursive macro ftw
macro_rules! dispatcher_route {
    ($method:ident) => {
        dispatch_route_normal!($method);
        dispatcher_route_debug!($method);
    };

    [$m:ident, $($t:ident),+] => {
        dispatcher_route!($m);
        dispatcher_route!($($t),+);
    }
}

// TRACE and CONNECT not allowed though. Doesn't seem like a big deal tbh.
dispatcher_route![get, head, options, put, delete, post, patch];

/*
 * Error catchers
 */

#[catch(404)]
fn page404() -> &'static str {
    "" // Empty 404 page.
}

/*
 * inner routes
 */

// TODO make macro
fn is_logged_in(jar: &CookieJar) -> bool {
    match jar.get("session").map(|c| c.value()) {
        Some(MASTER_KEY) => true,
        _ => false,
    }
}


#[post("/backapi/add", data = "<req>")]
fn add(req: Json<UpdateRouteRequest>, jar: &CookieJar) -> Status {
    if !is_logged_in(&jar) {
        return Status::Unauthorized;
    }

    match add_dyn_route(&req) {
        Ok(result) => {
            if result {
                Status::Created
            } else {
                Status::Ok
            }
        },
        Err(status) => status,
    }
}

#[post("/backapi/delete", data = "<req>")]
fn delete(req: Json<DeleteRouteRequest>, jar: &CookieJar) -> Status {
    if !is_logged_in(&jar) {
        Status::Unauthorized
    } else {
        delete_dyn_route(&req)
    }
}

#[post("/backapi/login", data="<login_req>")]
fn login_post(login_req: Json<LoginRequest>, jar: &CookieJar) -> Status {
    if login_req.key == MASTER_KEY {
        jar.add(
            Cookie::build(("session", MASTER_KEY))
                .path("/backapi")
        );
        Status::Ok
    } else {
        Status::Unauthorized
    }
}

// Check if logged in
#[get("/backapi/me")]
fn me(jar: &CookieJar) -> Status {
    if is_logged_in(jar) {
        Status::Ok
    } else {
        Status::Unauthorized
    }
}

#[get("/backapi/requests")]
fn get_requests(jar: &CookieJar) -> Result<Json<CapturedRequestFetch>, Status> {
    if is_logged_in(jar) {
        Ok(get_current_requests_json())
    } else {
        Err(Status::Unauthorized)
    }
}

#[get("/backapi/routes")]
fn get_routes(jar: &CookieJar) -> Result<Json<RouteListRequest>, Status> {
    if is_logged_in(jar) {
        Ok(Json(get_dyn_routes()))
    } else {
        Err(Status::Unauthorized)
    }
}

#[get("/backapi/listen/requests")]
fn listen_captured_reqs(channels: &State<EventChannels>, mut end: rocket::Shutdown) -> EventStream![] {
    let mut rx = channels.captured_reqs.subscribe();
    EventStream! {
        loop {
            select! {
                msg = rx.recv() => match msg {
                    Ok(text) => yield Event::data(text),
                    Err(rocket::tokio::sync::broadcast::error::RecvError::Lagged(_skipped)) => {
                        // The client missed 'skipped' number of messages. Not our problem.
                        continue;
                    },
                    Err(_) => break, // Channel closed
                },
                // Stop the stream if the server shuts down
                _ = &mut end => break,
            }
        }
    }
}

// Other backapi routes
#[get("/backapi/<_..>")]
fn other_backcall(jar: &CookieJar) -> Status {
    if !is_logged_in(jar) { // No route leak
        Status::Unauthorized
    } else {
        Status::NotFound
    }
}